name: VPS
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install 3X-UI
      run: |
        sudo bash <(curl -Ls https://raw.githubusercontent.com/mhsanaei/3x-ui/master/install.sh) v2.7.6 --no-input
    - uses: mxschmitt/action-tmate@v3
